insert into category (categoryid, name, description) values (1, 'Fruits', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into category (categoryid, name, description) values (2, 'Dairy', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into category (categoryid, name, description) values (3, 'Meat', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into category (categoryid, name, description) values (4, 'Bakery', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into category (categoryid, name, description) values (5, 'Frozen Foods', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into category (categoryid, name, description) values (6, 'Canned Goods', 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into category (categoryid, name, description) values (7, 'Snacks', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into category (categoryid, name, description) values (8, 'Beverages', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into category (categoryid, name, description) values (9, 'Vegetables', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.');
insert into category (categoryid, name, description) values (10, 'Pantry', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into category (categoryid, name, description) values (11, 'Household', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into category (categoryid, name, description) values (12, 'Personal Care', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into category (categoryid, name, description) values (13, 'Baby', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into category (categoryid, name, description) values (14, 'Pet', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into category (categoryid, name, description) values (15, 'Stationery', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into category (categoryid, name, description) values (16, 'Organic', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into category (categoryid, name, description) values (17, 'Diabetic Food', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into category (categoryid, name, description) values (18, 'Vegetarian', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into category (categoryid, name, description) values (19, 'International', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into category (categoryid, name, description) values (20, 'Alcohol', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
